version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
      - docker image pull splunk/splunk:latest
  build:
    commands:
      - pwd
    finally:
      - echo finally
