version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  build:
    commands:
      - pwd
      - python --version
      - docker version
      - set
      - docker image pull splunk/splunk:latest
    finally:
      - echo finally
