version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
      - docker image pull splunk/splunk:latest
      - SPLUNK_CID=$(docker run -d -p 8089 -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld -v $(pwd):/opt/splunk/etc/apps/splunk_as_a_service:rw splunk/splunk:latest)
  build:
    commands:
      - until docker logs --tail 100 $SPLUNK_CID 2>&1 | grep -m 1 "Ansible playbook complete"; do sleep 1 ; done
      - python ./tests/
    finally:
      - docker rm -fv $SPLUNK_CID
